Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2022-12, with the labels that each got.

#141 Add support for wait strategies
  src/main/docs/guide/modules-testcontainers.adoc
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
Labels: type: improvement

#137 [test-resources] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
Labels: relates-to: build

#143 [backport] Correct use of generics
  test-resources-client/src/main/java/io/micronaut/testresources/client/DefaultTestResourcesClient.java
Labels: bug

#149 Fix flat jar being deleted when directories change
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
Labels: type: bug

#151 Fix system property used to inject the server access token
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
Labels: type: bug
