Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2022-08, with the labels that each got.

#72 [test-resources] Update common files for branch master
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#50 Add support for Hibernate reactive
  buildSrc/src/main/groovy/io.micronaut.build.internal.hibernate-reactive-module.gradle
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/src/main/java/io/micronaut/testresources/hibernate/reactive/core/AbstractHibernateReactiveTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/src/main/java/io/micronaut/testresources/hibernate/reactive/core/HibernateReactiveSupport.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/src/testFixtures/groovy/io/micronaut/testresources/hibernate/reactive/core/Book.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/src/testFixtures/groovy/io/micronaut/testresources/hibernate/reactive/core/BookRepository.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/main/java/io/micronaut/testresources/hibernate/reactive/mariadb/HibernateReactiveMariaDBTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mariadb/StandaloneStartMariaDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mariadb/WithJdbcStartMariaDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/test/resources/application-jdbc.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/test/resources/application-standalone.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/test/resources/logback.xml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/main/java/io/micronaut/testresources/hibernate/reactive/mssql/HibernateReactiveMSSQLTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mssql/StandaloneStartMSSQLDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mssql/WithJdbcStartMSSQLDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/test/resources/application-jdbc.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/test/resources/application-standalone.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/test/resources/logback.xml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/main/java/io/micronaut/testresources/hibernate/reactive/mysql/HibernateReactiveMySQLTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mysql/StandaloneStartMySQLDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/mysql/WithJdbcStartMySQLDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/test/resources/application-jdbc.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/test/resources/application-standalone.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/test/resources/logback.xml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/main/java/io/micronaut/testresources/hibernate/reactive/oracle/HibernateReactiveOracleXETestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/test/groovy/io/micronaut/testresources/hibernate/reactive/oracle/StandaloneStartOracleXEDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/test/groovy/io/micronaut/testresources/hibernate/reactive/oracle/WithJdbcStartOracleXEDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/test/resources/application-jdbc.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/test/resources/application-standalone.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/test/resources/logback.xml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/main/java/io/micronaut/testresources/hibernate/reactive/postgresql/HibernateReactivePostgreSQLTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/postgresql/StandaloneStartPostgreSQLDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/test/groovy/io/micronaut/testresources/hibernate/reactive/postgresql/WithJdbcStartPostgreSQLDBTest.groovy
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/test/resources/application-jdbc.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/test/resources/application-standalone.yml
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/test/resources/logback.xml
  test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/AbstractR2DBCTestResourceProvider.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
Labels: type: improvement

#83 Let the user choose a custom db name
  src/main/docs/guide/modules-mongodb.adoc
  test-resources-mongodb/src/main/java/io/micronaut/testresources/mongodb/MongoDBTestResourceProvider.java
  test-resources-mongodb/src/test/groovy/io/micronaut/testresources/mongodb/CustomDbNameMongoDBTest.groovy
  test-resources-mongodb/src/test/resources/application-custom-db-name.yml
Labels: type: improvement

#84 Let the user tweak database parameters
  src/main/docs/guide/modules-databases-jdbc.adoc
  src/main/docs/guide/modules-databases-r2dbc.adoc
  test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mariadb/src/test/groovy/io/micronaut/testresources/jdbc/mariadb/StartMariaDBWithCustomizationsTest.groovy
  test-resources-jdbc/test-resources-jdbc-mariadb/src/test/resources/application-init-script.yml
  test-resources-jdbc/test-resources-jdbc-mariadb/src/test/resources/init.sql
  test-resources-jdbc/test-resources-jdbc-mariadb/src/test/resources/logback.xml
  test-resources-r2dbc/test-resources-r2dbc-mariadb/src/test/groovy/io/micronaut/testresources/r2dbc/mariadb/JdbcWithCustomizationMariaDBSQLTest.groovy
  test-resources-r2dbc/test-resources-r2dbc-mariadb/src/test/resources/application-customized-jdbc.yml
  test-resources-r2dbc/test-resources-r2dbc-mariadb/src/test/resources/init.sql
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
Labels: type: improvement

#85 Disable JAnsi output for the test resources service
  test-resources-server/src/main/resources/logback.xml
Labels: type: bug
