Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2022-06, with the labels that each got.

#2 [test-resources] Update common files for branch master
  .github/workflows/graalvm.yml
  MAINTAINING.md
Labels: relates-to: build

#11 First elements of documentation
  build.gradle
  gradle.properties
  src/main/docs/guide/architecture-client.adoc
  src/main/docs/guide/architecture-embedded.adoc
  src/main/docs/guide/architecture-server.adoc
  src/main/docs/guide/architecture-shared-server.adoc
  src/main/docs/guide/architecture.adoc
  src/main/docs/guide/implementing-test-resources.adoc
  src/main/docs/guide/introduction.adoc
  src/main/docs/guide/modules-databases-jdbc.adoc
  src/main/docs/guide/modules-databases-r2dbc.adoc
  src/main/docs/guide/modules-databases.adoc
  src/main/docs/guide/modules-kafka.adoc
  src/main/docs/guide/modules-mongodb.adoc
  src/main/docs/guide/modules-mqtt.adoc
  src/main/docs/guide/modules-neo4j.adoc
  src/main/docs/guide/modules-testcontainers.adoc
  src/main/docs/guide/modules.adoc
  src/main/docs/guide/quickStart.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#14 Add more options to test containers
  src/main/docs/guide/modules-testcontainers.adoc
  test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/CustomKafkaImageTest.groovy
  test-resources-testcontainers/build.gradle
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/GenericTestContainerProvider.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
Labels: type: improvement

#20 Add support for copying files to containers
  src/main/docs/guide/modules-testcontainers.adoc
  test-resources-kafka/src/test/groovy/io/micronaut/testresources/kafka/KafkaCustomConfigTest.groovy
  test-resources-kafka/src/test/resources/application-custom.yml
  test-resources-kafka/src/test/resources/example/kafka_server_jaas.conf
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
  test-resources-testcontainers/src/test/resources/some/file.txt
Labels: type: improvement

#19 Add support for RabbitMQ
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/modules-rabbitmq.adoc
  src/main/docs/guide/toc.yml
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
  test-resources-rabbitmq/build.gradle
  test-resources-rabbitmq/src/main/java/io/micronaut/testresources/rabbitmq/RabbitMQTestResourceProvider.java
  test-resources-rabbitmq/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-rabbitmq/src/test/groovy/io/micronaut/testresources/rabbitmq/AbstractRabbitMQSpec.groovy
  test-resources-rabbitmq/src/test/groovy/io/micronaut/testresources/rabbitmq/RabbitMQNotStartedTest.groovy
  test-resources-rabbitmq/src/test/groovy/io/micronaut/testresources/rabbitmq/RabbitMQStartedTest.groovy
  test-resources-rabbitmq/src/test/resources/logback.xml
Labels: type: improvement

#22 Refactor build
  buildSrc/src/main/groovy/io.micronaut.build.internal.jdbc-module.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.r2dbc-module.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.testcontainers-module.gradle
  test-resources-hivemq/build.gradle
  test-resources-jdbc/test-resources-jdbc-core/build.gradle
  test-resources-jdbc/test-resources-jdbc-mariadb/build.gradle
  test-resources-jdbc/test-resources-jdbc-mssql/build.gradle
  test-resources-jdbc/test-resources-jdbc-mysql/build.gradle
  test-resources-jdbc/test-resources-jdbc-oracle-xe/build.gradle
  test-resources-jdbc/test-resources-jdbc-postgresql/build.gradle
  test-resources-kafka/build.gradle
  test-resources-mongodb/build.gradle
  test-resources-neo4j/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-core/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-mariadb/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-mssql/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-mysql/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-oracle-xe/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-postgresql/build.gradle
  test-resources-rabbitmq/build.gradle
Labels: relates-to: build

#24 Optimize server with Micronaut AOT
  buildSrc/src/main/groovy/io.micronaut.build.internal.server-module.gradle
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  test-resources-server/build.gradle
Labels: type: improvement

#25 Add JVM startup options to the process parameters
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
Labels: type: improvement

#27 Add ability to tweak memory usage of containers
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/MemoryUnitParser.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainersConfiguration.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
Labels: type: improvement

#34 Add Hashicorp Vault support
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/modules-hashicorp-vault.adoc
  src/main/docs/guide/toc.yml
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
  test-resources-hashicorp-vault/build.gradle
  test-resources-hashicorp-vault/src/main/java/io/micronaut/testresources/mongodb/VaultTestResourceProvider.java
  test-resources-hashicorp-vault/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-hashicorp-vault/src/test/groovy/io/micronaut/testresources/mongodb/VaultStartedTest.groovy
  test-resources-hashicorp-vault/src/test/resources/logback.xml
Labels: enhancement

#33 Pass test resources configuration to create method
  test-resources-elasticsearch/src/main/java/io/micronaut/testresources/elasticsearch/ElasticsearchTestResourceProvider.java
  test-resources-hashicorp-vault/build.gradle
  test-resources-hashicorp-vault/src/main/java/io/micronaut/testresources/hashicorp/vault/VaultTestResourceProvider.java
  test-resources-hashicorp-vault/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-hashicorp-vault/src/test/groovy/io/micronaut/testresources/hashicorp/vault/VaultStartedTest.groovy
  test-resources-hashicorp-vault/src/test/resources/application-test.yml
  test-resources-hashicorp-vault/src/test/resources/bootstrap.yml
  test-resources-hivemq/src/main/java/io/micronaut/testresources/hivemq/HiveMQTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mariadb/src/main/java/io/micronaut/testresources/mariadb/MariaDBTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mssql/src/main/java/io/micronaut/testresources/mssql/MSSQLTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mysql/src/main/java/io/micronaut/testresources/mysql/MySQLTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-postgresql/src/main/java/io/micronaut/testresources/postgres/PostgreSQLTestResourceProvider.java
  test-resources-kafka/src/main/java/io/micronaut/testresources/kafka/KafkaTestResourceProvider.java
  test-resources-mongodb/src/main/java/io/micronaut/testresources/mongodb/MongoDBTestResourceProvider.java
  test-resources-neo4j/src/main/java/io/micronaut/testresources/neo4j/Neo4jTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/AbstractR2DBCTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-mariadb/src/main/java/io/micronaut/testresources/r2dbc/mariadb/R2DBCMariaDBTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-mssql/src/main/java/io/micronaut/testresources/r2dbc/mssql/R2DBCMSSQLTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-mysql/src/main/java/io/micronaut/testresources/r2dbc/mysql/R2DBCMySQLTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/main/java/io/micronaut/testresources/r2dbc/oracle/R2DBCOracleXETestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-postgresql/src/main/java/io/micronaut/testresources/r2dbc/postgres/R2DBCPostgreSQLTestResourceProvider.java
  test-resources-rabbitmq/src/main/java/io/micronaut/testresources/rabbitmq/RabbitMQTestResourceProvider.java
  test-resources-redis/src/main/java/io/micronaut/testresources/redis/RedisTestResourceProvider.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/AbstractTestContainersProviderTest.groovy
Labels: bug

#35 Add support for custom networks
  src/main/docs/guide/modules-testcontainers.adoc
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadata.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainers.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainersConfiguration.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/AbstractTestContainersProviderTest.groovy
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/CustomNetworkTest.groovy
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
  test-resources-testcontainers/src/test/resources/application-test.yml
Labels: type: improvement

#36 Implement classpath volume mapping
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainerMetadataSupport.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainersConfiguration.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainerMetadataSupportTest.groovy
  test-resources-testcontainers/src/test/resources/some/other-file.txt
Labels: type: improvement

#37 Tweak logging for Micronaut Test Resources server
  test-resources-server/src/main/java/io/micronaut/testresources/server/Application.java
  test-resources-server/src/main/resources/logback.xml
Labels: type: improvement

#42 Update Kafka image to 7.0.4
  test-resources-kafka/src/main/java/io/micronaut/testresources/kafka/KafkaTestResourceProvider.java
Labels: type: dependency-upgrade

#43 Add support for resolving R2DBC pool
  gradle/libs.versions.toml
  settings.gradle
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
  test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/AbstractR2DBCTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-core/src/main/java/io/micronaut/testresources/r2dbc/core/R2dbcSupport.java
  test-resources-r2dbc/test-resources-r2dbc-pool/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-pool/src/main/java/io/micronaut/testresources/r2dbc/pool/R2DBCPoolTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-pool/src/main/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/ReactiveBookRepository.groovy
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/StandaloneStartPostgreSQLTest.groovy
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/WithJdbcStartPostgreSQLTest.groovy
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/application-jdbc.yml
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/application-standalone.yml
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/logback.xml
Labels: type: improvement
