Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2022-07, with the labels that each got.

#57 Add more inference for Mongo
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/TestResourcesClasspath.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/TestResourcesClasspathTest.groovy
Labels: bug

#63 [test-resources] Update common files for branch master
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  gradlew.bat
Labels: relates-to: build

#64 Fix port file contents not always being readable
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
Labels: type: bug

#66 Update Maven quick start
  src/main/docs/guide/quickStart.adoc
Labels: type: docs

#67 [test-resources] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
Labels: relates-to: build
