Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2023-11, with the labels that each got.

#440 [test-resources] Update common files for branch master
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  .gitignore
  MAINTAINING.md
  SECURITY.md
Labels: relates-to: build

#432 Introduce test resources control panel
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle
  src/main/docs/guide/debugging-intro.adoc
  src/main/docs/guide/debugging.adoc
  src/main/docs/guide/modules-control-panel.adoc
  src/main/docs/guide/toc.yml
  src/main/docs/resources/img/test-resources-panel.jpg
  test-resources-control-panel/build.gradle
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/ControlPanelPropertyResolutionListener.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/DockerHealth.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/DockerHealthControlPanel.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/Status.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/TestResourcesContainer.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/TestResourcesControlPanel.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/TestResourcesPanelRegistration.java
  test-resources-control-panel/src/main/resources/views/docker/body.hbs
  test-resources-control-panel/src/main/resources/views/docker/detail.hbs
  test-resources-control-panel/src/main/resources/views/test-resources/body.hbs
  test-resources-control-panel/src/main/resources/views/test-resources/detail.hbs
  test-resources-core/src/main/java/io/micronaut/testresources/core/TestResourcesResolver.java
  test-resources-core/src/main/java/io/micronaut/testresources/core/ToggableTestResourcesResolver.java
  test-resources-elasticsearch/src/main/java/io/micronaut/testresources/elasticsearch/ElasticsearchTestResourceProvider.java
  test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/TestResourcesResolverLoader.java
  test-resources-hashicorp-vault/src/main/java/io/micronaut/testresources/hashicorp/vault/VaultTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/src/main/java/io/micronaut/testresources/hibernate/reactive/mariadb/HibernateReactiveMariaDBTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/src/main/java/io/micronaut/testresources/hibernate/reactive/mssql/HibernateReactiveMSSQLTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/src/main/java/io/micronaut/testresources/hibernate/reactive/mysql/HibernateReactiveMySQLTestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/main/java/io/micronaut/testresources/hibernate/reactive/oracle/HibernateReactiveOracleXETestResourceProvider.java
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/src/main/java/io/micronaut/testresources/hibernate/reactive/postgresql/HibernateReactivePostgreSQLTestResourceProvider.java
  test-resources-hivemq/src/main/java/io/micronaut/testresources/hivemq/HiveMQTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mariadb/src/main/java/io/micronaut/testresources/mariadb/MariaDBTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mssql/src/main/java/io/micronaut/testresources/mssql/MSSQLTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mysql/src/main/java/io/micronaut/testresources/mysql/MySQLTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-postgresql/src/main/java/io/micronaut/testresources/postgres/PostgreSQLTestResourceProvider.java
  test-resources-kafka/src/main/java/io/micronaut/testresources/kafka/KafkaTestResourceProvider.java
  test-resources-localstack/test-resources-localstack-core/src/main/java/io/micronaut/testresources/localstack/LocalStackTestResourceProvider.java
  test-resources-mongodb/src/main/java/io/micronaut/testresources/mongodb/MongoDBTestResourceProvider.java
  test-resources-neo4j/src/main/java/io/micronaut/testresources/neo4j/Neo4jTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-mariadb/src/main/java/io/micronaut/testresources/r2dbc/mariadb/R2DBCMariaDBTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-mssql/src/main/java/io/micronaut/testresources/r2dbc/mssql/R2DBCMSSQLTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-mysql/src/main/java/io/micronaut/testresources/r2dbc/mysql/R2DBCMySQLTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/main/java/io/micronaut/testresources/r2dbc/oracle/R2DBCOracleXETestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-pool/src/main/java/io/micronaut/testresources/r2dbc/pool/R2DBCPoolTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-postgresql/src/main/java/io/micronaut/testresources/r2dbc/postgres/R2DBCPostgreSQLTestResourceProvider.java
  test-resources-rabbitmq/src/main/java/io/micronaut/testresources/rabbitmq/RabbitMQTestResourceProvider.java
  test-resources-redis/src/main/java/io/micronaut/testresources/redis/RedisClusterTestResourceProvider.java
  test-resources-redis/src/main/java/io/micronaut/testresources/redis/RedisTestResourceProvider.java
  test-resources-server/build.gradle
  test-resources-server/src/main/java/io/micronaut/testresources/server/AccessFilter.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/PropertyResolutionListener.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesService.java
  test-resources-server/src/main/resources/application.properties
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/DockerSupport.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/GenericTestContainerProvider.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainers.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainersTest.groovy
Labels: enhancement

#445 Upgrade to Kotlin 1.9.20
  test-resources-extensions/test-resources-extensions-junit-platform/build.gradle
Labels: type: dependency-upgrade

#453 Add a server idle timeout
  gradle.properties
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerSettings.java
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClient.java
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesKeepAlive.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/ExpiryManager.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/Ping.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/PropertyResolutionListener.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesService.java
Labels: type: improvement

#463 Record resolution errors for control panel
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/ControlPanelPropertyResolutionListener.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/TestResourcesControlPanel.java
  test-resources-control-panel/src/main/java/io/micronaut/testresources/controlpanel/TestResourcesControlPanelBody.java
  test-resources-control-panel/src/main/resources/views/test-resources/body.hbs
  test-resources-control-panel/src/main/resources/views/test-resources/detail.hbs
  test-resources-core/src/main/java/io/micronaut/testresources/core/TestResourcesResolutionException.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/PropertyResolutionListener.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
Labels: type: enhancement

#464 Fix server not shutting down
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
  test-resources-server/src/main/resources/application.properties
Labels: bug
