Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2023-02, with the labels that each got.

#163 Migrate to new configuration asciidoc macro and build plugin 5.4.5
  .github/workflows/graalvm.yml
  settings.gradle
  src/main/docs/guide/modules-databases.adoc
  src/main/docs/guide/modules-hashicorp-vault.adoc
  src/main/docs/guide/modules-mqtt.adoc
  src/main/docs/guide/modules-testcontainers.adoc
Labels: type: docs

#161 Default to Oracle XE slim-faststart
  src/main/docs/guide/modules-databases.adoc
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/src/main/java/io/micronaut/testresources/hibernate/reactive/oracle/HibernateReactiveOracleXETestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-oracle-xe/src/main/java/io/micronaut/testresources/r2dbc/oracle/R2DBCOracleXETestResourceProvider.java
Labels: type: improvement

#117 Rename `Application` -> `TestResourcesService`
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
  test-resources-server/build.gradle
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesService.java
Labels: type: breaking

#165 Use a fat jar for the test resources service
  buildSrc/build.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.server-module.gradle
  test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/TestResourcesResolverLoader.java
  test-resources-server/build.gradle
Labels: bug

#150 [test-resources] Update common files for branch master
  .github/workflows/release-notes.yml
  .github/workflows/release.yml
Labels: relates-to: build
