Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2023-09, with the labels that each got.

#391 Fix resolution happening on event loop
  build.gradle
  gradle/libs.versions.toml
  test-resources-server/build.gradle
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
  test-resources-server/src/test/groovy/io/micronaut/testresources/server/TestResourcesControllerTest.groovy
  test-resources-server/src/testFixtures/java/io/micronaut/testresources/fixtures/FailingContainer.java
  test-resources-server/src/testFixtures/java/io/micronaut/testresources/fixtures/FailingTestResource.java
  test-resources-server/src/testFixtures/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
Labels: bug

#377 [test-resources] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
  test-resources-server/src/test/groovy/io/micronaut/testresources/server/TestResourcesControllerTest.groovy
  test-resources-server/src/testFixtures/java/io/micronaut/testresources/fixtures/FailingContainer.java
Labels: relates-to: build

#401 Add property to disable some test resources resolvers
  gradle.properties
  test-resources-core/src/main/java/io/micronaut/testresources/core/ToggableTestResourcesResolver.java
  test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/EmbeddedTestResourcesPropertyExpressionResolver.java
  test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/EmbeddedTestResourcesPropertySourceLoader.java
  test-resources-r2dbc/test-resources-r2dbc-pool/src/main/java/io/micronaut/testresources/r2dbc/pool/R2DBCPoolTestResourceProvider.java
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/groovy/io/micronaut/testresources/r2dbc/pool/R2DBCPoolDisablingTest.groovy
  test-resources-r2dbc/test-resources-r2dbc-pool/src/test/resources/application-r2dbc-pool-disabled.yml
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/AbstractTestContainersProvider.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/GenericTestContainerProvider.java
Labels: enhancement
