Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2023-03, with the labels that each got.

#176 Avoid trying to get datasource name from non-datasource expressions
  test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-oracle-xe/src/main/java/io/micronaut/testresources/oracle/xe/OracleXETestResourceProvider.java
Labels: type: bug

#173 [test-resources] Update common files for branch master
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradlew
  settings.gradle
Labels: relates-to: build

#182 Enable parallel build
  buildSrc/src/main/groovy/io.micronaut.build.internal.database-testing.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.hibernate-reactive-module.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.jdbc-module.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.kafka-testing.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.localstack-module.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.r2dbc-module.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.testcontainers-module.gradle
  buildSrc/src/main/groovy/io/micronaut/internal/ParallelGateService.java
  gradle.properties
  test-resources-kafka/build.gradle
  test-resources-localstack/test-resources-localstack-core/build.gradle
  test-resources-localstack/test-resources-localstack-dynamodb/build.gradle
  test-resources-localstack/test-resources-localstack-s3/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-pool/build.gradle
  test-resources-server/build.gradle
Labels: relates-to: build

#184 Only use kebab case for resolvable properties
  test-resources-elasticsearch/src/main/java/io/micronaut/testresources/elasticsearch/ElasticsearchTestResourceProvider.java
  test-resources-embedded/build.gradle
  test-resources-embedded/src/main/java/io/micronaut/testresources/embedded/EmbeddedTestResourcesPropertySourceLoader.java
  test-resources-embedded/src/test2/groovy/io/micronaut/testresources/embedded/FailingBean.groovy
  test-resources-embedded/src/test2/groovy/io/micronaut/testresources/embedded/InvalidTestResourcesTest.groovy
  test-resources-embedded/src/test2/groovy/io/micronaut/testresources/embedded/support/FailingResolver.java
  test-resources-embedded/src/test2/resources/META-INF/services/io.micronaut.testresources.core.TestResourcesResolver
  test-resources-embedded/src/test2/resources/logback.xml
  test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
Labels: type: bug

#186 [test-resources] Update common files for branch master
  .github/renovate.json
  .github/workflows/graalvm.yml
  .github/workflows/gradle.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#191 Document localstack support
  src/main/docs/guide/modules-localstack.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#190 Use Micronaut 4.0.0-M1
  build.gradle
  gradle/libs.versions.toml
  test-resources-server/build.gradle
Labels: type: dependency-upgrade

#194 [test-resources] Update common files for branch master
  .gitattributes
  .github/workflows/gradle.yml
Labels: relates-to: build

#193 Make all test resources client factory methods public
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java
Labels: type: improvement

#192 Fix close methods returning void
  test-resources-client/src/main/java/io/micronaut/testresources/client/DefaultTestResourcesClient.java
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClient.java
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertyExpressionResolver.java
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
  test-resources-server/src/test/groovy/io/micronaut/testresources/server/TestResourcesControllerTest.groovy
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainers.java
Labels: type: bug, type: breaking
