Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2023-12, with the labels that each got.

#466 [test-resources] Update common files for branch master
  .github/workflows/central-sync.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#478 Fix server startup utils
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-build-tools/src/test/groovy/io/micronaut/testresources/buildtools/ServerUtilsTest.groovy
Labels: bug

#481 Add links to guides for Micronaut Test Resources
  src/main/docs/guide/modules-databases.adoc
  src/main/docs/guide/modules-kafka.adoc
  src/main/docs/guide/testResourcesGuides.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#479 Close containers on shutdown
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
Labels: bug
