Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2023-06, with the labels that each got.

#312 Let the client factory find local configuration files
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientFactory.java
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertyExpressionResolver.java
  test-resources-client/src/main/java/io/micronaut/testresources/client/TestResourcesClientPropertySourceLoader.java
  test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestResourcesClientPropertiesTest.groovy
  test-resources-client/src/test/groovy/io/micronaut/testresources/client/TestResourcesClientTest.groovy
Labels: type: breaking

#298 [test-resources] Update common files for branch master
  .github/renovate.json
Labels: relates-to: build

#333 ci: slsa 1.7.0
  .github/workflows/release.yml
Labels: relates-to: build

#336 [test-resources] Update common files for branch master
  .github/workflows/release.yml
Labels: relates-to: build

#337 Make testcontainers dependencies managed
  gradle/libs.versions.toml
  test-resources-elasticsearch/build.gradle
  test-resources-hashicorp-vault/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-core/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mariadb/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mssql/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-mysql/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-oracle-xe/build.gradle
  test-resources-hibernate-reactive/test-resources-hibernate-reactive-postgresql/build.gradle
  test-resources-hivemq/build.gradle
  test-resources-jdbc/test-resources-jdbc-core/build.gradle
  test-resources-jdbc/test-resources-jdbc-mariadb/build.gradle
  test-resources-jdbc/test-resources-jdbc-mssql/build.gradle
  test-resources-jdbc/test-resources-jdbc-mysql/build.gradle
  test-resources-jdbc/test-resources-jdbc-oracle-xe/build.gradle
  test-resources-jdbc/test-resources-jdbc-postgresql/build.gradle
  test-resources-kafka/build.gradle
  test-resources-localstack/test-resources-localstack-core/build.gradle
  test-resources-mongodb/build.gradle
  test-resources-neo4j/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-core/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-mariadb/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-mssql/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-mysql/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-oracle-xe/build.gradle
  test-resources-r2dbc/test-resources-r2dbc-postgresql/build.gradle
  test-resources-rabbitmq/build.gradle
  test-resources-redis/build.gradle
  test-resources-testcontainers/build.gradle
Labels: enhancement

#339 Test resources to core RC1
  gradle/libs.versions.toml
Labels: type: dependency-upgrade

#343 Batch dependency upgrades for Micronaut Core 4.0.0-RC3
  gradle/libs.versions.toml
Labels: type: dependency-upgrade
