Repository micronaut-projects/micronaut-test-resources, pull requests merged in 2023-05, with the labels that each got.

#231 Implement test resources property provider factory
  buildSrc/src/main/groovy/io.micronaut.build.internal.test-resources-mntest-extension.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.test-resources-simple-module.gradle
  gradle/libs.versions.toml
  settings.gradle
  test-resources-extensions/test-resources-extensions-core/build.gradle
  test-resources-extensions/test-resources-extensions-core/src/main/java/io/micronaut/test/extensions/testresources/TestResourcesClientHolder.java
  test-resources-extensions/test-resources-extensions-core/src/main/java/io/micronaut/test/extensions/testresources/TestResourcesPropertiesFactory.java
  test-resources-extensions/test-resources-extensions-core/src/main/java/io/micronaut/test/extensions/testresources/TestResourcesPropertyProvider.java
  test-resources-extensions/test-resources-extensions-core/src/main/java/io/micronaut/test/extensions/testresources/annotation/TestResourcesProperties.java
  test-resources-extensions/test-resources-extensions-core/src/main/resources/META-INF/services/io.micronaut.test.support.TestPropertyProviderFactory
  test-resources-extensions/test-resources-extensions-core/src/test/java/io/micronaut/test/extensions/testresources/ConfigurationFilesTestResourcesPropertyProvidersTest.java
  test-resources-extensions/test-resources-extensions-core/src/test/java/io/micronaut/test/extensions/testresources/SimpleTestResourcesPropertyProvidersTest.java
  test-resources-extensions/test-resources-extensions-core/src/test/java/io/micronaut/test/extensions/testresources/TestResourcesPropertyProvidersTest.java
  test-resources-extensions/test-resources-extensions-core/src/test/resources/application-test.yml
  test-resources-extensions/test-resources-extensions-core/src/test/resources/logback.xml
  test-resources-extensions/test-resources-extensions-core/src/testFixtures/java/io/micronaut/test/extensions/testresources/FakeTestResourcesClient.java
  test-resources-extensions/test-resources-extensions-core/src/testFixtures/java/io/micronaut/test/extensions/testresources/FakeTestResourcesClientInjector.java
  test-resources-extensions/test-resources-extensions-core/src/testFixtures/java/io/micronaut/test/extensions/testresources/SomeBean.java
  test-resources-extensions/test-resources-extensions-core/src/testFixtures/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
Labels: type: improvement

#240 fix: handle accept license as string
  test-resources-jdbc/test-resources-jdbc-mssql/src/main/java/io/micronaut/testresources/mssql/MSSQLTestResourceProvider.java
  test-resources-jdbc/test-resources-jdbc-mssql/src/test/groovy/io/micronaut/testresources/mssql/MSSQLTestResourceProviderSpec.groovy
Labels: bug

#241 Add a `TestResourcesScope` annotation
  settings.gradle
  test-resources-build-tools/src/main/java/io/micronaut/testresources/buildtools/ServerUtils.java
  test-resources-extensions/test-resources-extensions-core/src/main/resources/META-INF/native-image/micronaut-test-resources-extensions-core/native-image.properties
  test-resources-extensions/test-resources-extensions-junit-platform/build.gradle
  test-resources-extensions/test-resources-extensions-junit-platform/src/koTest/kotlin/io/micronaut/test/extensions/junit5/AbstractScopedTest.kt
  test-resources-extensions/test-resources-extensions-junit-platform/src/koTest/kotlin/io/micronaut/test/extensions/junit5/ClassScopeTest.kt
  test-resources-extensions/test-resources-extensions-junit-platform/src/koTest/kotlin/io/micronaut/test/extensions/junit5/InheritedScopeTest.kt
  test-resources-extensions/test-resources-extensions-junit-platform/src/koTest/kotlin/io/micronaut/test/extensions/junit5/PackageScopeTest.kt
  test-resources-extensions/test-resources-extensions-junit-platform/src/koTest/kotlin/io/micronaut/test/extensions/junit5/ParentTestWithScope.kt
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/ScopeHolder.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/ScopeTestPropertyProviderFactory.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/TestResourcesScopeListener.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/annotation/ScopeNamingStrategy.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/annotation/TestResourcesScope.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/native-image/micronaut-test-resources-extension-junit-platform/reflect-config.json
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/io.micronaut.test.support.TestPropertyProviderFactory
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/AbstractScopedTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/BasicScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/InheritedScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/InheritedTraitScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/InterfaceWithScope.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/MultipleInheritanceOrder2ScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/MultipleInheritanceOrderScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/MultipleInheritanceScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/OverriddenScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/ParentTestWithScope.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/TraitWithScope.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/test/java/io/micronaut/test/extensions/junit5/AbstractScopedTest.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/test/java/io/micronaut/test/extensions/junit5/ClassScopeTest.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/test/java/io/micronaut/test/extensions/junit5/InheritedScopeTest.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/test/java/io/micronaut/test/extensions/junit5/PackageScopeTest.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/test/java/io/micronaut/test/extensions/junit5/ParentTestWithScope.kt
  test-resources-extensions/test-resources-extensions-junit-platform/src/test/java/io/micronaut/test/extensions/junit5/ScopeWithinClassTest.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/test/resources/application-test.yml
  test-resources-extensions/test-resources-extensions-junit-platform/src/testFixtures/java/io/micronaut/test/extensions/testresources/junit5/FakeTestResourcesClient.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/testFixtures/java/io/micronaut/test/extensions/testresources/junit5/FakeTestResourcesClientInjector.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/testFixtures/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
  test-resources-server/src/main/java/io/micronaut/testresources/server/TestResourcesController.java
  test-resources-testcontainers/src/main/java/io/micronaut/testresources/testcontainers/TestContainers.java
  test-resources-testcontainers/src/test/groovy/io/micronaut/testresources/testcontainers/TestContainersTest.groovy
  test-resources-testcontainers/src/test/resources/logback.xml
Labels: type: improvement

#242 Documentation for Micronaut test extensions
  src/main/docs/guide/extensions-core.adoc
  src/main/docs/guide/extensions-junit-platform.adoc
  src/main/docs/guide/extensions.adoc
  src/main/docs/guide/toc.yml
Labels: type: docs

#252 Make sure we can't use MariaDB instead of MySQL
  test-resources-jdbc/test-resources-jdbc-core/src/main/java/io/micronaut/testresources/jdbc/AbstractJdbcTestResourceProvider.java
Labels: type: bug

#251 Fix scope listeners
  test-resources-extensions/test-resources-extensions-junit-platform/build.gradle
  test-resources-extensions/test-resources-extensions-junit-platform/src/koTest/kotlin/io/micronaut/test/extensions/junit5/BeforeSpecScopeTest.kt
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/ScopeHolder.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/SpockScopeExtension.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/TestResourcesLauncherSessionListener.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/TestResourcesScopeListener.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/annotation/ScopeNamingStrategy.java
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/org.junit.platform.launcher.LauncherSessionListener
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/resources/META-INF/services/org.spockframework.runtime.extension.IGlobalExtension
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/SetupAnnotationScopeTest.groovy
  test-resources-extensions/test-resources-extensions-junit-platform/src/spockTest/groovy/io/micronaut/test/extensions/junit5/SharedAnnotationScopeTest.groovy
Labels: bug

#253 Fix test resources client not being cached
  test-resources-extensions/test-resources-extensions-junit-platform/src/main/java/io/micronaut/test/extensions/junit5/TestResourcesScopeListener.java
Labels: bug

#267 Fix YamlPropertySourceLoader being added on classpath
  test-resources-server/build.gradle
  test-resources-server/src/aot/aot.properties
Labels: bug

#261 [test-resources] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
  .github/workflows/graalvm.yml
Labels: relates-to: build

#272 [test-resources] Update common files for branch master
  .github/workflows/files-sync.yml
  .github/workflows/release.yml
Labels: relates-to: build

#295 [test-resources] Update common files for branch master
  .github/workflows/graalvm-dev.yml
  .github/workflows/graalvm-latest.yml
Labels: relates-to: build
